/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yiyicai_tvtrendapp_apkincrementtest_bsdiff_PatchUtils */

#ifndef _Included_com_yiyicai_tvtrendapp_apkincrementtest_bsdiff_PatchUtils
#define _Included_com_yiyicai_tvtrendapp_apkincrementtest_bsdiff_PatchUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yiyicai_tvtrendapp_apkincrementtest_bsdiff_PatchUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yiyicai_tvtrendapp_apkincrementtest_bsdiff_PatchUtils_patch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
